### ISSUE TITLE
That's a really nice theme! (no real issue)

### ISSUE THREAD

**Issue by moruzerinho6** [Nepumi/MusicMemories#1]
A issue like this would go better in a discussion section but since it isn't enabled on this repository I need to use issue.

I was looking into stepmania repositories on github and just found about this and it is so interesting, do you have a Discord, Reddit or twitter account so I can ask questions and how/why you made it? I'm really fascinated about what is there.

If you have a Discord, you can join [Project OutFox Discord server](https://discord.gg/cN4TjgQdcA) or add me Moru Zerinho6#9939

If you have reddit, [OutFox has a subreddit](https://www.reddit.com/r/OutFox) or you can [contact me](https://www.reddit.com/user/zerinho6)

If you have a twitter you can [contact me](https://twitter.com/Moru_zerinho6)

**Comment by moruzerinho6** [comment]
Gonna mention @Nepumi-Jr because the other account seems to be inactive? (Sorry in advance if it isn't)

**Comment by Nepumi-Jr** [comment]
**Thank you for your interest!** 
I have already joined in [Project OutFox Discord server](https://discord.gg/cN4TjgQdcA) *and friend request so.*

Thank you guy to make Stepmania 5.3 AKA. Outfox. It's so cool and a lot of new Lua stuff.
